algoritmo "MEDIA_TRES_NUMEROS"
// Disciplina   : [Algoritmos e Programação] 
// Professor   : Renan Costa Alencar 
// Função : Fazer a média aritmética de três números inteiros
// Autor : Renan Costa Alencar
// Data : 9/8/2007
// Seção de Declarações 
var
num1:inteiro
num2:inteiro
num3:inteiro
inicio
// Seção de Comandos
escreva("Digite tres numeros inteiros: ")
leia(num1)
leia(num2)
leia(num3)
escreva("A media aritmetica é: ")
escreva((num1+num2+num3)/3)
fimalgoritmo
