algoritmo "Q1_LISTA2"
// Disciplina   : [Algoritmos e Programação] 
// Professor   : Renan Costa Alencar 
// Função : verificas se dois numeros inteiros sao iguais
// Autor : Renan Costa Alencar
// Data : 18/8/2007
// Seção de Declarações 
var
a,b:inteiro
inicio
// Seção de Comandos
escreva("Digite dois numeros inteiros: ")
leia(a,b)
se(a=b) entao
        escreva("Os dois numeros sao iguais.")
senao
     escreva("Os dois sao diferentes.")
fimse
fimalgoritmo
