algoritmo "Q3_LISTA2"
// Disciplina   : [Algoritmos e Programação] 
// Professor   : Renan Costa Alencar 
// Função : verificar se o numero digitado eh impar ou par.
// Autor : Renan Costa Alencar
// Data : 18/8/2007
// Seção de Declarações 
var
x,y:inteiro
inicio
// Seção de Comandos
escreva("Digite numero: ")
leia(x,y)
se (x mod y=0) entao
   escreva(x," é divisivel por ",y)
senao
     escreva(x," não é divisivel por ",y)
fimse
fimalgoritmo
