algoritmo "CELSUS_PARA_FARENHEIT"
// Disciplina   : [Algoritmos e Programação] 
// Professor   : Renan Costa Alencar 
// Função : Converter a temperatura em Celsus para Farenheit
// Autor : Renan Costa Alencar
// Data : 9/8/2007
// Seção de Declarações 
var
tempc:inteiro
tempf:inteiro
soma:inteiro
inicio
// Seção de Comandos 
escreva("Digite a temperatura em Celsus: ")
leia(tempc)
tempf<-(180*(tempc+32))\100
escreva("Temperatura em Farenheit é gual a: ")
escreva(tempf)
fimalgoritmo
