/*INSERIR UMA LINHA DE DADOS( REGISTRO) NA TABELA :
*/
 

INSERT INTO TABELA (COLUNA1, COLUNA2, ...COLUNAn)

VALUES (VALOR1, “VALOR2”....VALORn)

 

INSERT INTO TABELA

VALUES (SELECT * FROM TABELA ...WHERE....)