DELIMITER //
CREATE PROCEDURE SP_ATUALIZAESTOQUE('ID_PROD' INT, 'QUANTIDADECOMPRADA' INT, VALORUNIT DECIMAL(9,2))
BEGIN
  DECLARE CONTADOR INT(11);
    SELECT COUNT(*) INTO CONTADOR FROM PRODUCTS WHERE PRODUCTCODE = ID_PROD;
    
    IF CONTADOR > 0 THEN
    UPDATE PRODUCTS SET QUANTITYINSTOCK = QUANTITYINSTOCK + QUANTIDADECOMPRADA, BUYPRICE = VALORUNIT
        WHERE PRODUCTCODE = ID_PROD;
  ELSE 
    INSERT INTO PRODUCTS (PRODUCTCODE, QUANTITYINSTOCK, BUYPRICE) 
        VALUES (ID_PROD, QUANTIDADECOMPRADA, VALORUNIT);
  END IF;
END //
DELIMITER ;

DELIMITER //
CREATE TRIGGER TRG_ENTRADAPRODUTO AFTER INSERT ON ORDERDETAILS
FOR EACH ROW
BEGIN
  CALL SP_ATUALIZAESTOQUE (NEW.ID_PROD, NEW.QUANTIDADECOMPRADA, NEW.VALORUNIT);
END //
DELIMITER ;