algoritmo "Q2_LISTA2"
// Disciplina   : [Algoritmos e Programação] 
// Professor   : Renan Costa Alencar 
// Função : verificar se o numero digitado eh impar ou par.
// Autor : Renan Costa Alencar
// Data : 18/8/2007
// Seção de Declarações 
var
x:inteiro
inicio
// Seção de Comandos
escreva("Digite numero: ")
leia(x)
se(x mod 2=0) entao
   escreva("O numero digitado e par.")
senao
     escreva("O numero e impar.")
fimse
fimalgoritmo
